[formatting]
indent_string = "    "
indent_tables = true
reorder_arrays = true
reorder_keys = true
trailing_newline = true

[[rule]]
include = ["**/Cargo.toml"]
keys = ["package"]

    [rule.formatting]
    reorder_keys = false
